### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by JamesLorimor** [hacs/integration#4303]
## System Information

version | core-2024.12.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.66-haos
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4988
Installed Version | 1.25.1
Stage | null
Available Repositories | 1350
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.0
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 30.8 GB
disk_used | 8.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | 

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 13, 2024 at 7:41 PM
-- | --
current_recorder_run | December 31, 2024 at 8:24 AM
estimated_db_size | 66.64 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Unable to install HACS.  I have uninstalled, restarted Home Assist, then tried to add HACS again.  I get 3 errors on restart:

Logger: homeassistant.data_entry_flow
Source: data_entry_flow.py:817
First occurred: 8:29:37 AM (1 occurrences)
Last logged: 8:29:37 AM

custom_components.hacs.config_flow::HacsFlowHandler calls async_show_progress without passing a progress task, this is not valid and will break in Home Assistant Core 2024.8. Please report it to the custom integration author

Log details (WARNING)
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 8:30:09 AM (5 occurrences)
Last logged: 8:30:09 AM

Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/themes", "/config/themes", True)])` at custom_components/hacs/frontend.py, line 25: hass.http.register_static_path(f"{URL_BASE}/themes", hass.config.path("themes")). This will stop working in Home Assistant 2025.7, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/frontend", "/config/custom_components/hacs/hacs_frontend", False)])` at custom_components/hacs/frontend.py, line 35: hass.http.register_static_path(f"{URL_BASE}/frontend", locate_dir(), cache_headers=False). This will stop working in Home Assistant 2025.7, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/iconset.js", "/config/custom_components/hacs/iconset.js", True)])` at custom_components/hacs/frontend.py, line 38: hass.http.register_static_path(. This will stop working in Home Assistant 2025.7, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles", "/config/www/community", True)])` at custom_components/hacs/frontend.py, line 53: hass.http.register_static_path(. This will stop working in Home Assistant 2025.7, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' accesses hass.components.frontend, which should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 63: hass.components.frontend.async_register_built_in_panel(. This will stop working in Home Assistant 2025.3, please create a bug report at https://github.com/hacs/integration/issues

Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 8:30:09 AM (1 occurrences)
Last logged: 8:30:09 AM

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/__init__.py", line 223, in async_setup_entry
    setup_result = await async_initialize_integration(hass=hass, config_entry=config_entry)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/__init__.py", line 209, in async_initialize_integration
    await async_try_startup()
  File "/config/custom_components/hacs/__init__.py", line 196, in async_try_startup
    startup_result = await async_startup()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/__init__.py", line 177, in async_startup
    hass.config_entries.async_setup_platforms(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'?

When I go to HACS, it says I'm running 1.25.1 and 63a5659 is available.  I click Update and then it says I'm on 1.25.1 and 2.0.1 is available.  Clicking Update does nothing.  Restart Home Assist and it says HACS is running 1.25.1 and 15cf380 is available.  Click Update and it says I'm on 1.25.1 and 2.0.1 is available.  Restart Home Assist and 15cf380 is available again.

It's now only giving me the last 2 errors, but I can't go any further.  I found another thread that gave a link to the direct download, but get a 404 error when I go there.

### Reproduction steps

All the steps I did are described in the issue.

### Debug logs

```text
I looked at the page to enable logging, but when I go to the Add-on store to get File Editor, there's nothing there.  I can't get the File Editor to edit configuration.yaml to enable debugging.
```

### Diagnostics dump

I don't have the option to Download Diagnostics when going to the HACS Integration and clicking on the 3 dots.

**Comment by ludeeus** [comment]
Too old.
Follow install instructions from website.
