### ISSUE TITLE
unable to update hacs from 1.15.2 to 1.24.5

### ISSUE THREAD

**Issue by 90abyss** [hacs/integration#2671]
### System Health details

System Health

version: core-2022.5.4
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.9.9
os_name: Linux
os_version: 5.10.108
arch: x86_64
timezone: America/Los_Angeles

GitHub API: ok
Github API Calls Remaining: 5000
Installed Version: 1.15.2
Stage: running
Available Repositories: 1050
Installed Repositories: 2

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

host_os: Home Assistant OS 7.6
update_channel: stable
supervisor_version: supervisor-2022.05.1
docker_version: 20.10.9
disk_total: 30.8 GB
disk_used: 15.3 GB
healthy: true
supported: failed to load: Unsupported
board: ova
supervisor_api: ok
version_api: ok
installed_addons: Samba share (9.6.1), File editor (5.3.3), Duck DNS (1.14.0), Studio Code Server (5.0.2), Z-Wave JS to MQTT (0.39.0), Node-RED (11.1.2), Mosquitto broker (6.1.2), Ring-MQTT with Video Streaming (5.0.1), Home Assistant Google Drive Backup (0.107.2), Portainer (2.0.0), Terminal & SSH (9.4.0), DOODS (2)

dashboards: 1
resources: 0
views: 3
mode: storage

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

i am not able to update hacs. i get this error when i click on update:

```
2022-05-13 00:18:20 INFO (MainThread) [backoff] Backing off async_download_file(...) for 0.9s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-13 00:18:21 INFO (MainThread) [backoff] Backing off async_download_file(...) for 0.4s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-13 00:18:22 INFO (MainThread) [backoff] Backing off async_download_file(...) for 2.4s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-13 00:18:24 INFO (MainThread) [backoff] Backing off async_download_file(...) for 7.9s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-13 00:18:32 ERROR (MainThread) [backoff] Giving up async_download_file(...) after 5 tries (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-13 00:18:32 ERROR (MainThread) [custom_components.hacs] Download was not completed
```

### Reproduction steps

1. click on update button
2.
3.
...

### Debug logs

```text
2022-05-12 23:41:29 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-12 23:41:29 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-12 23:41:29 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration deepstack_object which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-12 23:41:45 ERROR (MainThread) [homeassistant.components.cover] The opengarage platform for the cover integration does not support platform setup. Please remove it from your config.
2022-05-12 23:41:57 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2022-05-12 23:41:57 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2022-05-12 23:41:57 WARNING (MainThread) [homeassistant.setup] Setup of input_button is taking over 10 seconds.
2022-05-12 23:41:58 WARNING (MainThread) [homeassistant.setup] Setup of timer is taking over 10 seconds.
2022-05-12 23:41:58 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2022-05-12 23:41:58 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2022-05-12 23:41:58 WARNING (MainThread) [homeassistant.setup] Setup of counter is taking over 10 seconds.
2022-05-12 23:41:58 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2022-05-12 23:41:58 WARNING (MainThread) [homeassistant.setup] Setup of input_datetime is taking over 10 seconds.
2022-05-12 23:41:58 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform hassio is taking over 10 seconds.
2022-05-12 23:41:58 WARNING (MainThread) [homeassistant.components.update] Setup of update platform hassio is taking over 10 seconds.
2022-05-12 23:41:58 WARNING (MainThread) [homeassistant.setup] Setup of homekit_controller is taking over 10 seconds.
2022-05-12 23:41:58 ERROR (MainThread) [homeassistant.components.sensor] The cpuspeed platform for the sensor integration does not support platform setup. Please remove it from your config.
2022-05-12 23:41:58 WARNING (MainThread) [homeassistant.components.filesize.sensor] Configuration of the Filesize sensor platform in YAML is deprecated and will be removed in Home Assistant 2022.6; Your existing configuration has been imported into the UI automatically and can be safely removed from your configuration.yaml file
2022-05-12 23:42:03 ERROR (MainThread) [homeassistant.components.notify] Failed to initialize notification service webostv
2022-05-12 23:42:06 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that uses str for device registry entry_type. This is deprecated and will stop working in Home Assistant 2022.3, it should be updated to use DeviceEntryType instead. Please report this issue.
Stack (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 203, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 191, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 119, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 501, in _async_add_entity
    device = device_registry.async_get_or_create(**processed_dev_info)  # type: ignore[arg-type]
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 369, in async_get_or_create
    report(  # type: ignore[unreachable]
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 74, in report
    _LOGGER.warning(msg, stack_info=True)
2022-05-12 23:42:06 WARNING (MainThread) [homeassistant.components.onvif] The date/time on AC (UTC) is '2022-05-13 08:02:39+00:00', which is different from the system '2022-05-13 06:42:04.713921+00:00', this could lead to authentication issues
2022-05-12 23:42:06 WARNING (MainThread) [async_upnp_client.profiles.dlna] Only InstanceID 0 is supported
2022-05-12 23:42:07 WARNING (MainThread) [async_upnp_client.profiles.dlna] Only InstanceID 0 is supported
2022-05-12 23:42:12 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform amcrest is taking over 10 seconds.
2022-05-12 23:42:12 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform amcrest is taking over 10 seconds.
2022-05-12 23:42:13 WARNING (MainThread) [homeassistant.components.camera] Setup of camera platform amcrest is taking over 10 seconds.
2022-05-12 23:42:13 WARNING (MainThread) [homeassistant.components.camera] Setup of camera platform amcrest is taking over 10 seconds.
2022-05-12 23:42:13 WARNING (MainThread) [homeassistant.components.camera] Setup of camera platform amcrest is taking over 10 seconds.
2022-05-12 23:42:13 WARNING (MainThread) [homeassistant.components.camera] Setup of camera platform amcrest is taking over 10 seconds.
2022-05-12 23:42:45 ERROR (stream_worker) 
2022-05-12 23:42:47 WARNING (MainThread) [asyncio] socket.send() raised exception.
2022-05-12 23:42:47 WARNING (MainThread) [asyncio] socket.send() raised exception.
2022-05-12 23:42:47 WARNING (MainThread) [asyncio] socket.send() raised exception.
2022-05-12 23:42:47 WARNING (MainThread) [asyncio] socket.send() raised exception.
2022-05-12 23:42:47 WARNING (MainThread) [asyncio] socket.send() raised exception.
2022-05-12 23:42:47 WARNING (MainThread) [asyncio] socket.send() raised exception.
2022-05-12 23:42:47 WARNING (MainThread) [asyncio] socket.send() raised exception.
2022-05-12 23:42:47 WARNING (MainThread) [asyncio] socket.send() raised exception.
2022-05-12 23:42:47 WARNING (MainThread) [asyncio] socket.send() raised exception.
2022-05-12 23:42:47 WARNING (MainThread) [asyncio] socket.send() raised exception.
2022-05-12 23:42:47 WARNING (MainThread) [asyncio] socket.send() raised exception.
2022-05-12 23:42:47 WARNING (MainThread) [asyncio] socket.send() raised exception.
2022-05-12 23:42:47 WARNING (MainThread) [asyncio] socket.send() raised exception.
2022-05-12 23:42:47 WARNING (MainThread) [asyncio] socket.send() raised exception.
2022-05-12 23:42:55 WARNING (MainThread) [homeassistant.components.sensor] Updating amcrest sensor took longer than the scheduled update interval 0:00:10
2022-05-12 23:42:55 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.837_nvr_sd_used is taking over 10 seconds
2022-05-12 23:42:55 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.frontyard_cam_sd_used is taking over 10 seconds
2022-05-12 23:42:55 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.frontdoor_cam_sd_used is taking over 10 seconds
2022-05-12 23:42:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.frontyard_cam is taking over 10 seconds
2022-05-12 23:42:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.frontdoor_cam_2 is taking over 10 seconds
2022-05-12 23:43:00 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x2028:1:0x0702]: async_initialize: all attempts have failed: [DeliveryError('[0x2028:1:0x0702]: Message send failure'), DeliveryError('[0x2028:1:0x0702]: Message send failure'), DeliveryError('[0x2028:1:0x0702]: Message send failure'), DeliveryError('[0x2028:1:0x0702]: Message send failure')]
2022-05-12 23:43:03 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x2028:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('[0x2028:1:0x0006]: Message send failure'), DeliveryError('[0x2028:1:0x0006]: Message send failure'), DeliveryError('[0x2028:1:0x0006]: Message send failure'), DeliveryError('[0x2028:1:0x0006]: Message send failure')]
2022-05-12 23:43:05 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xADF9:1:0x0300]: async_initialize: all attempts have failed: [DeliveryError('[0xadf9:1:0x0300]: Message send failure'), DeliveryError('[0xadf9:1:0x0300]: Message send failure'), DeliveryError('[0xadf9:1:0x0300]: Message send failure'), DeliveryError('[0xadf9:1:0x0300]: Message send failure')]
2022-05-12 23:43:05 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x4738:1:0x0008]: async_initialize: all attempts have failed: [DeliveryError('[0x4738:1:0x0008]: Message send failure'), DeliveryError('[0x4738:1:0x0008]: Message send failure'), DeliveryError('[0x4738:1:0x0008]: Message send failure'), DeliveryError('[0x4738:1:0x0008]: Message send failure')]
2022-05-12 23:43:05 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x4738:1:0x0300]: async_initialize: all attempts have failed: [DeliveryError('[0x4738:1:0x0300]: Message send failure'), DeliveryError('[0x4738:1:0x0300]: Message send failure'), DeliveryError('[0x4738:1:0x0300]: Message send failure'), DeliveryError('[0x4738:1:0x0300]: Message send failure')]
2022-05-12 23:43:05 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xADF9:1:0x0008]: async_initialize: all attempts have failed: [DeliveryError('[0xadf9:1:0x0008]: Message send failure'), DeliveryError('[0xadf9:1:0x0008]: Message send failure'), DeliveryError('[0xadf9:1:0x0008]: Message send failure'), DeliveryError('[0xadf9:1:0x0008]: Message send failure')]
2022-05-12 23:43:05 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x4738:1:0x0702]: async_initialize: all attempts have failed: [DeliveryError('[0x4738:1:0x0702]: Message send failure'), DeliveryError('[0x4738:1:0x0702]: Message send failure'), DeliveryError('[0x4738:1:0x0702]: Message send failure'), DeliveryError('[0x4738:1:0x0702]: Message send failure')]
2022-05-12 23:43:05 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x4738:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('[0x4738:1:0x0006]: Message send failure'), DeliveryError('[0x4738:1:0x0006]: Message send failure'), DeliveryError('[0x4738:1:0x0006]: Message send failure'), DeliveryError('[0x4738:1:0x0006]: Message send failure')]
2022-05-12 23:43:05 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xADF9:1:0x0702]: async_initialize: all attempts have failed: [DeliveryError('[0xadf9:1:0x0702]: Message send failure'), DeliveryError('[0xadf9:1:0x0702]: Message send failure'), DeliveryError('[0xadf9:1:0x0702]: Message send failure'), DeliveryError('[0xadf9:1:0x0702]: Message send failure')]
2022-05-12 23:43:05 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xADF9:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('[0xadf9:1:0x0006]: Message send failure'), DeliveryError('[0xadf9:1:0x0006]: Message send failure'), DeliveryError('[0xadf9:1:0x0006]: Message send failure'), DeliveryError('[0xadf9:1:0x0006]: Message send failure')]
2022-05-12 23:43:05 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x791D:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('[0x791d:1:0x0006]: Message send failure'), DeliveryError('[0x791d:1:0x0006]: Message send failure'), DeliveryError('[0x791d:1:0x0006]: Message send failure'), DeliveryError('[0x791d:1:0x0006]: Message send failure')]
2022-05-12 23:43:08 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x791D:1:0x0008]: async_initialize: all attempts have failed: [DeliveryError('[0x791d:1:0x0008]: Message send failure'), DeliveryError('[0x791d:1:0x0008]: Message send failure'), DeliveryError('[0x791d:1:0x0008]: Message send failure'), DeliveryError('[0x791d:1:0x0008]: Message send failure')]
2022-05-12 23:43:09 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x791D:1:0x0300]: async_initialize: all attempts have failed: [DeliveryError('[0x791d:1:0x0300]: Message send failure'), DeliveryError('[0x791d:1:0x0300]: Message send failure'), DeliveryError('[0x791d:1:0x0300]: Message send failure'), DeliveryError('[0x791d:1:0x0300]: Message send failure')]
2022-05-12 23:43:10 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x328D:1:0x0008]: async_initialize: all attempts have failed: [DeliveryError('[0x328d:1:0x0008]: Message send failure'), DeliveryError('[0x328d:1:0x0008]: Message send failure'), DeliveryError('[0x328d:1:0x0008]: Message send failure'), DeliveryError('[0x328d:1:0x0008]: Message send failure')]
2022-05-12 23:43:10 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xB633:1:0x0300]: async_initialize: all attempts have failed: [DeliveryError('[0xb633:1:0x0300]: Message send failure'), DeliveryError('[0xb633:1:0x0300]: Message send failure'), DeliveryError('[0xb633:1:0x0300]: Message send failure'), DeliveryError('[0xb633:1:0x0300]: Message send failure')]
2022-05-12 23:43:10 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xB633:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('[0xb633:1:0x0006]: Message send failure'), DeliveryError('[0xb633:1:0x0006]: Message send failure'), DeliveryError('[0xb633:1:0x0006]: Message send failure'), DeliveryError('[0xb633:1:0x0006]: Message send failure')]
2022-05-12 23:43:10 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x328D:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('[0x328d:1:0x0006]: Message send failure'), DeliveryError('[0x328d:1:0x0006]: Message send failure'), DeliveryError('[0x328d:1:0x0006]: Message send failure'), DeliveryError('[0x328d:1:0x0006]: Message send failure')]
2022-05-12 23:43:10 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xB633:1:0x0702]: async_initialize: all attempts have failed: [DeliveryError('[0xb633:1:0x0702]: Message send failure'), DeliveryError('[0xb633:1:0x0702]: Message send failure'), DeliveryError('[0xb633:1:0x0702]: Message send failure'), DeliveryError('[0xb633:1:0x0702]: Message send failure')]
2022-05-12 23:43:10 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x328D:1:0x0702]: async_initialize: all attempts have failed: [DeliveryError('[0x328d:1:0x0702]: Message send failure'), DeliveryError('[0x328d:1:0x0702]: Message send failure'), DeliveryError('[0x328d:1:0x0702]: Message send failure'), DeliveryError('[0x328d:1:0x0702]: Message send failure')]
2022-05-12 23:43:10 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x328D:1:0x0300]: async_initialize: all attempts have failed: [DeliveryError('[0x328d:1:0x0300]: Message send failure'), DeliveryError('[0x328d:1:0x0300]: Message send failure'), DeliveryError('[0x328d:1:0x0300]: Message send failure'), DeliveryError('[0x328d:1:0x0300]: Message send failure')]
2022-05-12 23:43:10 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x791D:1:0x0702]: async_initialize: all attempts have failed: [DeliveryError('[0x791d:1:0x0702]: Message send failure'), DeliveryError('[0x791d:1:0x0702]: Message send failure'), DeliveryError('[0x791d:1:0x0702]: Message send failure'), DeliveryError('[0x791d:1:0x0702]: Message send failure')]
2022-05-12 23:43:12 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xB633:1:0x0008]: async_initialize: all attempts have failed: [DeliveryError('[0xb633:1:0x0008]: Message send failure'), DeliveryError('[0xb633:1:0x0008]: Message send failure'), DeliveryError('[0xb633:1:0x0008]: Message send failure'), DeliveryError('[0xb633:1:0x0008]: Message send failure')]
2022-05-12 23:43:19 ERROR (stream_worker) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/homeassistant/homeassistant/components/stream/__init__.py", line 338, in _run_worker
    stream_worker(
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 538, in stream_worker
    muxer.mux_packet(first_keyframe)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 233, in mux_packet
    self._av_output.mux(packet)
  File "av/container/output.pyx", line 211, in av.container.output.OutputContainer.mux
  File "av/container/output.pyx", line 217, in av.container.output.OutputContainer.mux_one
  File "av/container/output.pyx", line 183, in av.container.output.OutputContainer.start_encoding
  File "av/container/core.pyx", line 292, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: '<none>'; last error log: [mp4] dimensions not set
2022-05-12 23:49:05 INFO (MainThread) [backoff] Backing off async_download_file(...) for 0.5s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:05 INFO (MainThread) [backoff] Backing off async_download_file(...) for 0.6s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:05 INFO (MainThread) [backoff] Backing off async_download_file(...) for 0.9s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:05 INFO (MainThread) [backoff] Backing off async_download_file(...) for 0.4s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:06 INFO (MainThread) [backoff] Backing off async_download_file(...) for 0.3s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:06 INFO (MainThread) [backoff] Backing off async_download_file(...) for 0.6s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:06 INFO (MainThread) [backoff] Backing off async_download_file(...) for 0.4s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:06 INFO (MainThread) [backoff] Backing off async_download_file(...) for 1.3s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:06 INFO (MainThread) [backoff] Backing off async_download_file(...) for 1.8s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:06 INFO (MainThread) [backoff] Backing off async_download_file(...) for 0.6s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:06 INFO (MainThread) [backoff] Backing off async_download_file(...) for 0.0s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:06 INFO (MainThread) [backoff] Backing off async_download_file(...) for 4.3s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:07 INFO (MainThread) [backoff] Backing off async_download_file(...) for 1.9s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:07 INFO (MainThread) [backoff] Backing off async_download_file(...) for 4.2s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:08 INFO (MainThread) [backoff] Backing off async_download_file(...) for 0.8s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:09 INFO (MainThread) [backoff] Backing off async_download_file(...) for 7.4s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:09 ERROR (MainThread) [backoff] Giving up async_download_file(...) after 5 tries (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:11 ERROR (MainThread) [backoff] Giving up async_download_file(...) after 5 tries (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:11 ERROR (MainThread) [backoff] Giving up async_download_file(...) after 5 tries (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:16 ERROR (MainThread) [backoff] Giving up async_download_file(...) after 5 tries (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-12 23:49:16 ERROR (MainThread) [custom_components.hacs] Download was not completed [timeout() got an unexpected keyword argument 'loop']
2022-05-12 23:49:16 ERROR (MainThread) [custom_components.hacs] Download was not completed [timeout() got an unexpected keyword argument 'loop']
2022-05-12 23:49:16 ERROR (MainThread) [custom_components.hacs] Download was not completed [timeout() got an unexpected keyword argument 'loop']
2022-05-12 23:49:16 ERROR (MainThread) [custom_components.hacs] Download was not completed [timeout() got an unexpected keyword argument 'loop']
2022-05-13 00:16:01 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that uses str for device registry entry_type. This is deprecated and will stop working in Home Assistant 2022.3, it should be updated to use DeviceEntryType instead. Please report this issue.
Stack (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 203, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 191, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 119, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 501, in _async_add_entity
    device = device_registry.async_get_or_create(**processed_dev_info)  # type: ignore[arg-type]
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 369, in async_get_or_create
    report(  # type: ignore[unreachable]
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 74, in report
    _LOGGER.warning(msg, stack_info=True)
2022-05-13 00:18:20 INFO (MainThread) [backoff] Backing off async_download_file(...) for 0.9s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-13 00:18:21 INFO (MainThread) [backoff] Backing off async_download_file(...) for 0.4s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-13 00:18:22 INFO (MainThread) [backoff] Backing off async_download_file(...) for 2.4s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-13 00:18:24 INFO (MainThread) [backoff] Backing off async_download_file(...) for 7.9s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-13 00:18:32 ERROR (MainThread) [backoff] Giving up async_download_file(...) after 5 tries (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-13 00:18:32 ERROR (MainThread) [custom_components.hacs] Download was not completed
2022-05-13 00:21:53 INFO (MainThread) [backoff] Backing off async_download_file(...) for 0.9s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-13 00:21:54 INFO (MainThread) [backoff] Backing off async_download_file(...) for 1.1s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-13 00:21:55 INFO (MainThread) [backoff] Backing off async_download_file(...) for 3.1s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-13 00:21:59 INFO (MainThread) [backoff] Backing off async_download_file(...) for 1.9s (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-13 00:22:01 ERROR (MainThread) [backoff] Giving up async_download_file(...) after 5 tries (TypeError: timeout() got an unexpected keyword argument 'loop')
2022-05-13 00:22:01 ERROR (MainThread) [custom_components.hacs] Download was not completed
```

**Comment by ludeeus** [comment]
Downgrade Home Assistant or run the install script from the website.

**Comment by 90abyss** [comment]
> Downgrade Home Assistant or run the install script from the website.

How do i run the install script from the website? Which script? And from where? Can you please elaborate?

**Comment by 90abyss** [comment]
Another qs: which version should I downgrade HA to?

**Comment by ningcol** [comment]
> Another qs: which version should I downgrade HA to?

Did you solve this problem please?
