### ISSUE TITLE
HACS is starting up - forever

### ISSUE THREAD

**Issue by asimmetrico** [hacs/integration#1378]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| 112      |
|0.112.4    |
|Hassio |

## Checklist

- [ ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ ] I have enabled debug logging for my installation.
- [ ] I have filled out the issue template to the best of my ability.
- [ ] I have read <https://hacs.xyz/docs/issues>
- [ ] This issue is related to the backend of HACS.
- [ ] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I get the message HACS is starting up forever

### Steps to reproduce

1. 1. 1.

## Debug logs

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

Logger: homeassistant.config_entries
Source: helpers/storage.py:119
First occurred: 8:01:46 (1 occurrences)
Last logged: 8:01:46

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 220, in async_setup
    hass, self
  File "/config/custom_components/hacs/__init__.py", line 81, in async_setup_entry
    startup_result = await hacs_startup()
  File "/config/custom_components/hacs/__init__.py", line 175, in hacs_startup
    if not await hacs.data.restore():
  File "/config/custom_components/hacs/hacsbase/data.py", line 85, in restore
    hacs = await async_load_from_store(self.hacs.hass, "hacs")
  File "/config/custom_components/hacs/store.py", line 11, in async_load_from_store
    restored = await store.async_load()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 101, in async_load
    return await self._load_task
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 119, in _async_load
    if data["version"] == self.version:
KeyError: 'version'

</details>

<!-- IssueTemplateID: issue_backend -->

**Comment by kinchahoy** [comment]
I'm having the same issue. Tried uninstalling and reinstalling HACS per the documentation and it still doesn't work. 

Error in logs says:

Logger: aiohttp.server
Source: custom_components/hacs/config_flow.py:90
First occurred: 3:40:18 PM (1 occurrences)
Last logged: 3:40:18 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 186, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 73, in post
    "show_advanced_options": data["show_advanced_options"],
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 129, in async_init
    flow, flow.init_step, data, init_done
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 201, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/hacs/config_flow.py", line 82, in async_step_init
    return await self.async_step_user()
  File "/config/custom_components/hacs/config_flow.py", line 90, in async_step_user
    if hacs.configuration.config_type == "yaml":
AttributeError: 'NoneType' object has no attribute 'config_type'

**Comment by thoompje** [comment]
Exactly the same here.

Home Assistant is saying all the time: Home Assistant is starting, not everything will be available until it is finished.


And all my HACS apps are broken, how can we fix this?

**Comment by asimmetrico** [comment]
So I suppose there is an issue. In the log there is a reference to the
version. Maybe this HACS version doesn't support the Hassio 0.113. In the
documentation it says from 0.110 and following.

I don't know how to proceed.

Best

Al

Il giorno lun 13 lug 2020 alle ore 20:31 thoompje <notifications@github.com>
ha scritto:

**Comment by LEJOUI** [comment]
I’m also vinding that in HA 0.113beta HACS seems to be stuck on starting which causes somehow that the update fails and HA rolls back.

**Comment by ludeeus** [comment]
```
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 119, in _async_load
    if data["version"] == self.version:
KeyError: 'version'
```

@ascillato  You get this if you tried HACS in the past and there are still data files with the old format, of your data files are corrupt.

Delete all files containing `hacs` under `.storage` and restart Home Assistant to solve it.

@LEJOUI I run both dev and beta versions of Home Assistant, both works as it should with current version of HACS.

**Comment by nuaimat** [comment]
I am seeing different error in the logs, 

2020-09-08 01:54:43 ERROR (MainThread) [custom_components.hacs.factory] Limych/media_player.linkplay - Repository is archived.

**Comment by nirkons** [comment]
Hi,

I followed the guide and got stuck also at HACS is starting forever, turned on debugging and there were some github error 500 on a few repositories.

I tried removing all the files and integration, restarting HASS and trying to install again but now I'm getting github limit error
```
Log Details (ERROR)
Logger: aiohttp.server
Source: custom_components/hacs/helpers/functions/information.py:48
First occurred: 5:33:11 PM (2 occurrences)
Last logged: 5:34:17 PM

Error handling request
Traceback (most recent call last):
  File "/config/custom_components/hacs/helpers/functions/information.py", line 45, in get_repository
    repository = await github.get_repo(repository_full_name)
  File "/usr/local/lib/python3.8/site-packages/aiogithubapi/github.py", line 55, in get_repo
    response = await self.client.get(endpoint=_endpoint, headers=_headers)
  File "/usr/local/lib/python3.8/site-packages/aiogithubapi/client.py", line 36, in get
    response = await async_call_api(
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/aiogithubapi/helpers.py", line 80, in async_call_api
    raise AIOGitHubAPIRatelimitException("GitHub Ratelimit error")
aiogithubapi.common.exceptions.AIOGitHubAPIRatelimitException: GitHub Ratelimit error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 145, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 201, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/hacs/config_flow.py", line 41, in async_step_user
    if await self._test_token(user_input["token"]):
  File "/config/custom_components/hacs/config_flow.py", line 66, in _test_token
    await get_repository(session, token, "hacs/org")
  File "/config/custom_components/hacs/helpers/functions/information.py", line 48, in get_repository
    raise HacsException(exception)
custom_components.hacs.helpers.classes.exceptions.HacsException: GitHub Ratelimit error
```


not sure what to do now

**Comment by jrial** [comment]
> replaced the token but still same issue, not sure what to do now, ill wait an hour and try again but does it make sense that HACS used up all the github usage for the entire hour in a few minutes while setting up?

@nirkons No, and I found out that at least in my case, that error message is nonsense. You can easily verify for yourself whether your rate limit has been exceeded by looking at https://api.github.com/rate_limit

Did you manage to get it working in the end? If so, care to share your solution?

**Comment by nirkons** [comment]
> > replaced the token but still same issue, not sure what to do now, ill wait an hour and try again but does it make sense that HACS used up all the github usage for the entire hour in a few minutes while setting up?
> 
> @nirkons No, and I found out that at least in my case, that error message is nonsense. You can easily verify for yourself whether your rate limit has been exceeded by looking at https://api.github.com/rate_limit - in my case it was complaining about the rate limit when it hadn't even performed a single API call that would eat into my rate limit budget.
> 
> Did you manage to get it working in the end? If so, care to share your solution?

I just let it be and came back a day later and it was working... so try that haha

**Comment by flostingapplesauce** [comment]
Same started happening here. It did not help to wipe .storage, so I tried entirely removing /config and starting from scratch, and same. A fresh install of HACS is not working,

**Comment by jrial** [comment]
> Same started happening here. It did not help to wipe .storage, so I tried entirely removing /config and starting from scratch, and same. A fresh install of HACS is not working,

I managed to get it working. I believe I just had to install it, wait a good while, and then restart HA, possibly twice. At some point it simply started working fine.

**Comment by QNimbus** [comment]
I can confirm - I just installed HACS on a relatively fresh install of **Home Assistant**. I did take quite some time but after a while (I'm guessing 10 minutes or so) the `Home Assistant is starting, not everything will be available until it is finished` message disappeared. I did not have to restart **Home Assistant** manually in the meantime. Hope this feedback helps with this issue.

**Comment by athanassis** [comment]
Just wanted to report another incident for everyone to know.
I got also the same message about HACS starting up and also "HACS is disabled... less than 1 hour" with a red indication. I restarted several times, with leaving ~1h in between. In the last restart I left it there overnight, and next morning was OK.

That was with latest to date Home Assistant 2021.2.3, and HACS 1.11.3

**Comment by JamesLodge** [comment]
Same issue here. It's yet to resolve, but its only been about 10 minutes. 

New installation using the OVA. 

HACS 1.11.3
Home Assistant 2021.3.4

**Comment by frederickjh** [comment]
I am experiencing the same thing after upgrading to 2021.4.6 and then upgrading HACS to 1.11.3 yesterday. I reboot several times yesterday uninstalled and reinstalled HACS and then waited over night but HACS is still starting up. Rebooting today did not change this. 

This morning I am getting the following two errors:

```
Logger: homeassistant
Source: custom_components/hacs/hacsbase/hacs.py:195
First occurred: 08:17:44 (1 occurrences)
Last logged: 08:17:44

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 140, in startup_tasks
    await self.handle_critical_repositories()
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 195, in handle_critical_repositories
    critical = json.loads(critical.content)
AttributeError: 'list' object has no attribute 'content'
```
and 
```
Logger: custom_components.hacs
Source: custom_components/hacs/repositories/integration.py:64
Integration: HACS (documentation, issues)
First occurred: 08:17:36 (1 occurrences)
Last logged: 08:17:36

<Integration hacs/integration> Could not read manifest.json [encoding without a string argument]
```

Did a search today on closed issues for the second message and found #2039.  In that issue it say to see #2038 which says that the newest version of HACS (1.12.1) fixes this in case someone else is experiencing this.

**Comment by chrbratt** [comment]
Same here after 2021.4.6

**Comment by a1ad** [comment]
@chrbratt yup, same here

**Comment by frederickjh** [comment]
I upgraded HACS to 1.12.3 and did not have this issue. So, it looks like the fix in 1.12.1 works.

So for anyone finding this issue that is having this problem, upgrade HACS to version 1.12.1 or higher to fix this.

**Comment by a1ad** [comment]
Confirmed

**Comment by hugoduraes** [comment]
I'm on 1.12.3 and it still happens. Installed it yesterday and right after it I got this error. Waited until this morning it was ok but as soon I installed a custom component, it errored again! I've checked my GitHub api usage and for all resources I get `used = 0`!

**Comment by ryanzzz** [comment]
I have the same issue today.
Home Assistant OS core-2021.8.8
HACS 1.14.1.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hacs/operational/setup.py:182
Integration: HACS (documentation, issues)
First occurred: 10:10:29 PM (1 occurrences)
Last logged: 10:10:29 PM

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 27, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 75, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 99, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 182, in async_hacs_startup
    reset = datetime.fromtimestamp(int(hacs.github.client.ratelimits.reset))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by raoulteeuwenPE** [comment]
I also have "HACS is starting up" the last couple of days. Hasn't resolved after reboots. I'm on core-2021.8.8 and HACS 1.15.0 (afaik all sw is the latest). Logs include

Error doing job: Task exception was never retrieved
7:20:36 AM – (ERROR) HACS (custom integration)
0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.github.com/repos/hacs/default/contents/removed')
7:20:36 AM – (ERROR) HACS (custom integration) - message first occurred at 7:20:35 AM and shows up 4 times

2021-08-31 07:20:35 ERROR (MainThread) [custom_components.hacs] 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.github.com/repos/hacs/default/contents/removed')
2021-08-31 07:20:36 ERROR (MainThread) [custom_components.hacs] 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.github.com/repos/hacs/default/contents/plugin')
2021-08-31 07:20:36 ERROR (MainThread) [custom_components.hacs] 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.github.com/repos/hacs/default/contents/theme')
2021-08-31 07:20:36 ERROR (MainThread) [custom_components.hacs] 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.github.com/repos/hacs/default/contents/integration')

Traceback (most recent call last):
File "/config/custom_components/hacs/hacsbase/hacs.py", line 139, in startup_tasks
await self.recurring_tasks_installed()
File "/config/custom_components/hacs/hacsbase/hacs.py", line 263, in recurring_tasks_installed
await self.handle_critical_repositories()
File "/config/custom_components/hacs/hacsbase/hacs.py", line 172, in handle_critical_repositories
critical = await self.async_github_get_hacs_default_file("critical")
File "/config/custom_components/hacs/base.py", line 232, in async_github_get_hacs_default_file
response = await self.githubapi.repos.contents.get(
File "/usr/local/lib/python3.9/site-packages/aiogithubapi/namespaces/contents.py", line 50, in get
response = await self._client.async_call_api(
File "/usr/local/lib/python3.9/site-packages/aiogithubapi/client.py", line 124, in async_call_api
response.data = await result.json()
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1097, in json
raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.github.com/repos/hacs/default/contents/critical')
2021-08-31 07:24:20 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{% if value_json.zappi[0].ectp1 is defined %}
{{ value_json.zappi[0].ectp1 }}
{% else %}
0

**Comment by dannymertens** [comment]
And we can join the club :-(

![image](https://user-images.githubusercontent.com/46963011/131463913-cd90a8cd-d469-4aa3-884e-213b8326838b.png)

In the Custom repositories I also have now a very long lists with integrations, cards? that probably not complete load? there for sure not things that I configured before 

![image](https://user-images.githubusercontent.com/46963011/131464160-833f19a8-2777-432d-93d9-85bceefa7b41.png)

Error

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/helpers/functions/get_list_from_default.py:35
Integration: HACS (documentation, issues)
First occurred: 09:33:56 (6 occurrences)
Last logged: 09:33:59

0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.github.com/repos/hacs/default/contents/netdaemon')
0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.github.com/repos/hacs/default/contents/plugin')
0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.github.com/repos/hacs/default/contents/appdaemon')
0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.github.com/repos/hacs/default/contents/integration')
0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.github.com/repos/hacs/default/contents/theme')

System information

## System Health

version | core-2021.8.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.53
arch | aarch64
timezone | Europe/Brussels

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4748
Installed Version | 1.15.0
Stage | startup
Available Repositories | 941
Installed Repositories | 39

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | September 26, 2021, 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.2
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 113.9 GB
disk_used | 16.4 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Visual Studio Code (3.6.2), deCONZ (6.10.0), Samba Backup (4.5.0), Assistant Relay (0.7.4), ADB - Android Debug Bridge (0.8.0), Tautulli (2.3.0), Node-RED (10.0.0), Mosquitto broker (6.0.1), File editor (5.3.3), MariaDB (2.4.0), Eufy Home Assistant MQTT Bridge (1.21.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 18
-- | --
resources | 25
views | 56
mode | storage

</details>

Thanks in advance for looking in to this!
