### ISSUE TITLE
HACS does not start after update to 0.16.0

### ISSUE THREAD

**Issue by paulbdavis** [hacs/integration#744]
## Version of HACS

0.16.0

## Describe the bug

HACS fails to start up when hass is started

## Debug log

```text

2019-10-27 11:52:39 ERROR (MainThread) [homeassistant.setup] Error during setup of component hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 167, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/hacs/__init__.py", line 37, in async_setup
    config[DOMAIN], config[DOMAIN].get("options")
  File "/config/custom_components/hacs/hacsbase/configuration.py", line 44, in from_dict
    country=options.get("country"),
AttributeError: 'NoneType' object has no attribute 'get'


```

**Comment by paulbdavis** [comment]
The configuration in my `configuration.yaml` did not change between the releases

```yaml
hacs:
  token:  !secret hacs_github_api_key
```

**Comment by ludeeus** [comment]
As a workaround change your configuration to this:

```yaml
hacs:
  token:  !secret hacs_github_api_key
  options:
    release_limit: 5
```
5 is the default value so it will not have an impact on how HACS works.

**Comment by paulbdavis** [comment]
That works for now, thanks for the quick response
