### ISSUE TITLE
HACS not loading completely because of Errors with Loading Repositiories

### ISSUE THREAD

**Issue by almostserious** [hacs/integration#2440]
## System Health

version | core-2021.12.9
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.4.0-92-generic
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.19.2
Stage | running
Available Repositories | 938
Downloaded Repositories | 41

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Ubuntu 20.04.3 LTS
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 19.03.8
disk_total | 109.0 GB
disk_used | 87.3 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | SSH & Web Terminal (10.0.1), Node-RED (10.3.1), AdGuard Home (4.4.2), Mosquitto broker (6.0.1), Glances (0.14.1), MariaDB (2.4.0), WireGuard (0.6.0), Studio Code Server (3.7.0), Portainer (2.0.0), Nginx Proxy Manager (0.11.0), Vaultwarden (Bitwarden) (0.14.1), phpMyAdmin (0.6.0), Home Assistant Google Drive Backup (0.105.2), Rhasspy Assistant (2.5.11), IPerf3 Server (0.1), Firefly III (3609591), snapcast-server (0.25), diyHue (1.5.0), deCONZ (6.11.1), TooGoodToGo Home Assistant MQTT Bridge (1.9.2-2), diyHue Beta (1.5.0), File editor (5.3.3), librespot (v0.3.1.2), Mopidy (6e49c79), Nextcloud for Home Assistant (23.0.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 29
views | 19
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I get some errors when setting up HACS at Startup.
This leads to the Custom Repositories constantly being greyed out.

The error shows up as some of my custom_integrations being archived. 
In the beginning I had this error also for different customs integrations like the Node-Red Companion.
After deleting the hacs.repositories this was fixed and the only remaining one with issues posting is 
`Integration PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor`

### Reproduction steps

1. Restart HACS
2. Getting Errors in the Log
3. Custom Repositories is greyed out

### Debug logs

```text
2022-01-11 09:33:36 DEBUG (MainThread) [custom_components.hacs] <Integration PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor> Getting repository information
2022-01-11 09:33:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/hacs/base.py", line 580, in startup_tasks
await self.recurring_tasks_installed()
File "/config/custom_components/hacs/base.py", line 678, in recurring_tasks_installed
await self.handle_critical_repositories()
File "/config/custom_components/hacs/base.py", line 656, in handle_critical_repositories
await critical_queue.execute()
File "/config/custom_components/hacs/utils/queue_manager.py", line 69, in execute
await asyncio.gather(*local_queue)
File "/config/custom_components/hacs/utils/decorator.py", line 22, in wrapper
await function(*args, **kwargs)
File "/config/custom_components/hacs/repositories/integration.py", line 104, in update_repository
if not await self.common_update(ignore_issues, force) and not force:
File "/config/custom_components/hacs/utils/decorator.py", line 22, in wrapper
await function(*args, **kwargs)
File "/config/custom_components/hacs/repositories/base.py", line 516, in common_update
await self.common_update_data(ignore_issues=ignore_issues, force=force)
File "/config/custom_components/hacs/repositories/base.py", line 942, in common_update_data
raise HacsRepositoryArchivedException("Repository is archived.")
custom_components.hacs.exceptions.HacsRepositoryArchivedException: Repository is archived.
```

**Comment by ludeeus** [comment]
Randomly deleting files will cause more issues...
Restart Home Assistant from the UI, and this should resolve itself

**Comment by greasypete** [comment]
Same here, HACS still starting:


Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 562, in startup_tasks
    await self.async_load_default_repositories()
  File "/config/custom_components/hacs/base.py", line 706, in async_load_default_repositories
    for item in await self.async_github_get_hacs_default_file(HacsCategory.REMOVED):
  File "/config/custom_components/hacs/base.py", line 441, in async_github_get_hacs_default_file
    response = await self.async_github_api_method(
  File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Timeout of 20 reached while waiting for https://api.github.com/repos/hacs/default/contents/removed

**Comment by wasyl00** [comment]
In the same boat: 

HACS is still starting after updating to 1.19.3

```
Traceback (most recent call last):
File "/config/custom_components/hacs/base.py", line 562, in startup_tasks
await self.async_load_default_repositories()
File "/config/custom_components/hacs/base.py", line 706, in async_load_default_repositories
for item in await self.async_github_get_hacs_default_file(HacsCategory.REMOVED):
File "/config/custom_components/hacs/base.py", line 441, in async_github_get_hacs_default_file
response = await self.async_github_api_method(
File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Timeout of 20 reached while waiting for https://api.github.com/repos/hacs/default/contents/removed
```

**Comment by dutch-erik** [comment]
I do have same issue (HACS doesn’t start), restart HA doesn’t help. I noticed that when I disable and enable the integration HACS starts as it should be. But new restart of HA issue occurs again. However not sure if it happens all the time.

I do have a trace, the way as descriped, but I don’t know where to look for or what I should/can post.

**Comment by WalterDSU** [comment]
me too.


![image](https://user-images.githubusercontent.com/91654066/149607412-5244f836-24bd-4810-aaf4-10e2859c3234.png)
Logger: homeassistant
Source: custom_components/hacs/repositories/base.py:946
Integration: HACS (documentation, issues)
First occurred: 11:06:51 (1 occurrences)
Last logged: 11:06:51

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 580, in startup_tasks
    await self.recurring_tasks_installed()
  File "/config/custom_components/hacs/base.py", line 678, in recurring_tasks_installed
    await self.handle_critical_repositories()
  File "/config/custom_components/hacs/base.py", line 656, in handle_critical_repositories
    await critical_queue.execute()
  File "/config/custom_components/hacs/utils/queue_manager.py", line 69, in execute
    await asyncio.gather(*local_queue)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    await function(*args, **kwargs)
  File "/config/custom_components/hacs/repositories/integration.py", line 104, in update_repository
    if not await self.common_update(ignore_issues, force) and not force:
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    await function(*args, **kwargs)
  File "/config/custom_components/hacs/repositories/base.py", line 516, in common_update
    await self.common_update_data(ignore_issues=ignore_issues, force=force)
  File "/config/custom_components/hacs/repositories/base.py", line 946, in common_update_data
    raise HacsRepositoryArchivedException("Repository is archived.")
custom_components.hacs.exceptions.HacsRepositoryArchivedException: Repository is archived.

**Comment by dutch-erik** [comment]
As mentioned above... after each restart of HA, HACS:

`HACS is starting up, during this time some information might be missing or incorrect`

```
2022-01-15 16:30:18 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):

File "/config/custom_components/hacs/base.py", line 562, in startup_tasks
await self.async_load_default_repositories()

File "/config/custom_components/hacs/base.py", line 706, in async_load_default_repositories
for item in await self.async_github_get_hacs_default_file(HacsCategory.REMOVED):

File "/config/custom_components/hacs/base.py", line 441, in async_github_get_hacs_default_file
response = await self.async_github_api_method(

File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
raise HacsException(_exception)

custom_components.hacs.exceptions.HacsException: Timeout of 20 reached while waiting for https://api.github.com/repos/hacs/default/contents/removed
```

HACS will not start until I disable and enable the HACS integration.
This started after upgrading to 1.19.

**Comment by Hypercookie** [comment]
I have the same issue
HACS seems to be starting up but the "custom repositories" button is grayed out (so startup seems to have failed).
Log shows the same error as above.
It also does not work when disabling and enabling the HACS integration.

**Comment by greasypete** [comment]
For me helped a downgrade to 1.19.2; after reboot hacs started and also updated repositories again including custom repositories

Cheers Stefan

**Comment by WRLPDZ** [comment]
Hi,
Same for me but I think that this problem appear since other error with "Aftership"
"Aftership" repo was long time ago removed from my HACS.
From some time I have info that this repo should be removed but it is not present in my system even it's folder do not exist,
but still I have info on main HACS page to remove it and clicking on remove button do nothing that reload of HACS page and again info is present.
Since that time I also see error: Task exception was never retrieved.
I don't know if that  is corelated but maybe it's some clue.

**Comment by Mike5357** [comment]
Also having a similar issue; "Custom Repositories" is greyed out, and it notifies me that a repository was removed as its no longer working but clicking "Remove" does not remove it from the UI. Instead the log just reports "[custom_components.hacs] Could not use repository with ID 234079212 ('NoneType' object has no attribute 'get_releases')" when clicking it and says "Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/hacs/repositories/base.py", line 889, in async_get_legacy_repository_object
repository = await github.get_repo(self.data.full_name, etag)"
