### ISSUE TITLE
Can't uninstall integration repo. "Path is blocked from removal"

### ISSUE THREAD

**Issue by TTLucian** [hacs/integration#1893]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.11.0 |
| Home Assistant version     | 2021.2.2 |
| Installation method for HA | HyperV virtual machine image|

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I can't seem to be able to uninstall integration repositories. Log shows error: "Path /config/custom_components/ is blocked from removal"
I removed HACS completely and reinstalled. After restoring (reinstalling) all integrations and frontend repos, I get the same error.

### Steps to reproduce

1. Add/install integration repository in HACS through UI
2. Uninstall integration repository in HACS through UI

## Debug logs

<details>
  <summary>Logs</summary>

```

2021-02-09 20:46:26 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-09 20:46:26 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-09 20:46:26 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-09 20:46:26 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-09 20:46:26 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for mikrotik_router which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-09 20:46:26 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-09 20:46:31 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sun2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-09 20:46:31 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for climate_group which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-09 20:46:32 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for xiaomi_cloud_map_extractor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-09 20:46:33 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-09 20:46:35 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for illuminance which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-09 20:46:35 DEBUG (MainThread) [custom_components.hacs] Configuration type: flow
2021-02-09 20:46:35 INFO (MainThread) [custom_components.hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.11.0
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2021-02-09 20:46:35 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.WEBSOCKET
2021-02-09 20:46:35 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.FRONTEND
2021-02-09 20:46:36 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.CATEGORIES
2021-02-09 20:46:36 INFO (MainThread) [custom_components.hacs] HACS is enabled
2021-02-09 20:46:37 ERROR (MainThread) [frontend.js.latest.202101277] https://hass.lthome.eu/hacsfiles/lovelace-swipe-navigation/swipe-navigation.js:17:95 Uncaught TypeError: Cannot read property 'shadowRoot' of null
2021-02-09 20:46:37 DEBUG (MainThread) [custom_components.hacs] Can update 263 repositories
2021-02-09 20:46:37 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.HACS_REPO
2021-02-09 20:46:37 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Checking repository.
2021-02-09 20:46:38 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.11.0
2021-02-09 20:46:39 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> All (0) checks passed
2021-02-09 20:46:39 INFO (MainThread) [custom_components.hacs] <Integration hacs/integration> Registration completed
2021-02-09 20:46:39 INFO (MainThread) [custom_components.hacs] Restore started
2021-02-09 20:46:41 INFO (MainThread) [custom_components.hacs] Restore done
2021-02-09 20:46:41 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.SENSOR
2021-02-09 20:46:41 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.WAITING
2021-02-09 20:46:41 INFO (MainThread) [custom_components.hacs] Setup complete, waiting for Home Assistant before startup tasks starts
2021-02-09 20:46:41 INFO (MainThread) [custom_components.hacs] HACS is enabled
2021-02-09 20:46:44 WARNING (MainThread) [homeassistant.components.vacuum] Setup of vacuum platform xiaomi_miio is taking over 10 seconds.
2021-02-09 20:46:45 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.ground_floor is taking over 10 seconds
2021-02-09 20:46:46 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.STARTUP
2021-02-09 20:46:46 INFO (MainThread) [custom_components.hacs] setup task HacsSetupTask.CATEGORIES
2021-02-09 20:46:46 DEBUG (SyncWorker_10) [custom_components.hacs] Starting setup task: Extra stores
2021-02-09 20:46:46 DEBUG (SyncWorker_10) [custom_components.hacs] Enable category: HacsCategory.INTEGRATION
2021-02-09 20:46:46 DEBUG (SyncWorker_10) [custom_components.hacs] Enable category: HacsCategory.PLUGIN
2021-02-09 20:46:46 DEBUG (SyncWorker_10) [custom_components.hacs] Enable category: HacsCategory.THEME
2021-02-09 20:46:46 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.critical'. Content did not change
2021-02-09 20:46:46 INFO (MainThread) [custom_components.hacs] Loading known repositories
2021-02-09 20:46:46 DEBUG (MainThread) [custom_components.hacs] Got 93 elements for HacsCategory.REMOVED
2021-02-09 20:46:46 DEBUG (MainThread) [custom_components.hacs] Can update 262 repositories, items in queue 3
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] Got 207 elements for HacsCategory.PLUGIN
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] Got 478 elements for HacsCategory.INTEGRATION
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] Got 62 elements for HacsCategory.THEME
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] Starting recurring background task for installed repositories
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] <Integration lukas-hetzenecker/home-assistant-remote> Checking repository.
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Getting repository information
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] <Plugin PiotrMachowski/lovelace-xiaomi-vacuum-map-card> Getting repository information
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] <Plugin bramkragten/weather-card> Getting repository information
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] <Plugin ofekashery/vertical-stack-in-card> Getting repository information
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-slider-entity-row> Getting repository information
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] <Plugin gadgetchnnel/lovelace-card-templater> Getting repository information
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] <Integration thomasloven/hass-browser_mod> Getting repository information
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] <Plugin artem-sedykh/mini-climate-card> Getting repository information
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] <Plugin htmltiger/numberbox-card> Getting repository information
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-fold-entity-row> Getting repository information
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] <Theme wowgamr/animated-weather-card> Getting repository information
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/stack-in-card> Getting repository information
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] <Plugin kalkih/mini-graph-card> Getting repository information
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> Getting repository information
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] Did not update PiotrMachowski/lovelace-xiaomi-vacuum-map-card, content was not modified
2021-02-09 20:46:47 DEBUG (MainThread) [custom_components.hacs] Did not update hacs/integration, content was not modified
2021-02-09 20:46:48 DEBUG (MainThread) [custom_components.hacs] Did not update thomasloven/lovelace-slider-entity-row, content was not modified
2021-02-09 20:46:48 DEBUG (MainThread) [custom_components.hacs] Did not update thomasloven/hass-browser_mod, content was not modified
2021-02-09 20:46:48 DEBUG (MainThread) [custom_components.hacs] Did not update kalkih/mini-graph-card, content was not modified
2021-02-09 20:46:48 DEBUG (MainThread) [custom_components.hacs] Did not update wowgamr/animated-weather-card, content was not modified
2021-02-09 20:46:48 DEBUG (MainThread) [custom_components.hacs] Did not update gadgetchnnel/lovelace-card-templater, content was not modified
2021-02-09 20:46:48 DEBUG (MainThread) [custom_components.hacs] Did not update artem-sedykh/mini-climate-card, content was not modified
2021-02-09 20:46:48 DEBUG (MainThread) [custom_components.hacs] Did not update bramkragten/weather-card, content was not modified
2021-02-09 20:46:48 DEBUG (MainThread) [custom_components.hacs] Did not update htmltiger/numberbox-card, content was not modified
2021-02-09 20:46:48 DEBUG (MainThread) [custom_components.hacs] Did not update AlexxIT/SonoffLAN, content was not modified
2021-02-09 20:46:48 DEBUG (MainThread) [custom_components.hacs] Did not update custom-cards/stack-in-card, content was not modified
2021-02-09 20:46:48 DEBUG (MainThread) [custom_components.hacs] Did not update ofekashery/vertical-stack-in-card, content was not modified
2021-02-09 20:46:48 DEBUG (MainThread) [custom_components.hacs] Did not update thomasloven/lovelace-fold-entity-row, content was not modified
2021-02-09 20:46:48 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/remote_homeassistant> Running checks against 3.1
2021-02-09 20:46:49 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/remote_homeassistant> All (0) checks passed
2021-02-09 20:46:49 INFO (MainThread) [custom_components.hacs] <Integration custom-components/remote_homeassistant> Registration completed
2021-02-09 20:46:52 DEBUG (MainThread) [custom_components.hacs] <Plugin jcwillox/lovelace-canary> Getting repository information
2021-02-09 20:46:52 DEBUG (MainThread) [custom_components.hacs] <Integration tomaae/homeassistant-mikrotik_router> Getting repository information
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] <Integration gregoryduckworth/GoogleGeocode-HASS> Getting repository information
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-layout-card> Getting repository information
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-auto-entities> Getting repository information
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] <Plugin royto/logbook-card> Getting repository information
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] <Integration daenny/climate_group> Getting repository information
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] <Plugin iantrich/text-divider-row> Getting repository information
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] <Plugin nielsfaber/scheduler-card> Getting repository information
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] <Integration zachowj/hass-node-red> Getting repository information
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] <Plugin maykar/lovelace-swipe-navigation> Getting repository information
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] Did not update jcwillox/lovelace-canary, content was not modified
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] Did not update tomaae/homeassistant-mikrotik_router, content was not modified
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] Did not update gregoryduckworth/GoogleGeocode-HASS, content was not modified
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] Did not update thomasloven/lovelace-layout-card, content was not modified
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] Did not update thomasloven/lovelace-auto-entities, content was not modified
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] Did not update daenny/climate_group, content was not modified
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] Did not update royto/logbook-card, content was not modified
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/climate.programmable_thermostat> Getting repository information
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] Did not update iantrich/text-divider-row, content was not modified
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] Did not update zachowj/hass-node-red, content was not modified
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] <Plugin benct/lovelace-xiaomi-vacuum-card> Getting repository information
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] Did not update nielsfaber/scheduler-card, content was not modified
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] Did not update maykar/lovelace-swipe-navigation, content was not modified
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] <Integration Limych/ha-average> Getting repository information
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] Did not update custom-components/climate.programmable_thermostat, content was not modified
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] Did not update benct/lovelace-xiaomi-vacuum-card, content was not modified
2021-02-09 20:46:53 DEBUG (MainThread) [custom_components.hacs] Did not update Limych/ha-average, content was not modified
2021-02-09 20:46:54 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-card-mod> Getting repository information
2021-02-09 20:46:54 DEBUG (MainThread) [custom_components.hacs] Did not update thomasloven/lovelace-card-mod, content was not modified
2021-02-09 20:46:56 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] <Plugin jcwillox/lovelace-paper-buttons-row> Getting repository information
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] <Plugin benct/lovelace-multiple-entity-row> Getting repository information
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] <Plugin maxwroc/battery-state-card> Getting repository information
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] <Integration PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor> Getting repository information
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/button-card> Getting repository information
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] <Integration nielsfaber/scheduler-component> Getting repository information
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] <Plugin nervetattoo/simple-thermostat> Getting repository information
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] <Plugin kalkih/mini-media-player> Getting repository information
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] <Plugin denysdovhan/vacuum-card> Getting repository information
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] Did not update jcwillox/lovelace-paper-buttons-row, content was not modified
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] Did not update benct/lovelace-multiple-entity-row, content was not modified
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] Did not update nervetattoo/simple-thermostat, content was not modified
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] Did not update nielsfaber/scheduler-component, content was not modified
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] Did not update custom-cards/button-card, content was not modified
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] Did not update kalkih/mini-media-player, content was not modified
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] Did not update maxwroc/battery-state-card, content was not modified
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] Did not update denysdovhan/vacuum-card, content was not modified
2021-02-09 20:46:58 DEBUG (MainThread) [custom_components.hacs] Did not update PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor, content was not modified
2021-02-09 20:46:58 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.study is taking over 10 seconds
2021-02-09 20:47:01 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2021-02-09 20:47:03 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.critical'. Content did not change
2021-02-09 20:47:03 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-02-09 20:47:03 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-02-09 20:47:03 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.repositories'. Content did not change
2021-02-09 20:47:03 DEBUG (MainThread) [custom_components.hacs] Recurring background task for installed repositories done
2021-02-09 20:47:03 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2021-02-09 20:47:03 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.RUNNING
2021-02-09 20:47:06 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2021-02-09 20:47:49 DEBUG (MainThread) [custom_components.hacs] Running uninstall for custom-components/climate.programmable_thermostat
2021-02-09 20:47:49 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/climate.programmable_thermostat> Getting repository information
2021-02-09 20:47:50 DEBUG (MainThread) [custom_components.hacs] Did not update custom-components/climate.programmable_thermostat, content was not modified
2021-02-09 20:47:50 INFO (MainThread) [custom_components.hacs] <Integration custom-components/climate.programmable_thermostat> Uninstalling
2021-02-09 20:47:50 ERROR (MainThread) [custom_components.hacs] <Integration custom-components/climate.programmable_thermostat> Path /config/custom_components/ is blocked from removal
2021-02-09 20:47:50 ERROR (MainThread) [custom_components.hacs] Could not uninstall
2021-02-09 20:48:23 DEBUG (MainThread) [custom_components.hacs] Running not_new for custom-components/remote_homeassistant
2021-02-09 20:48:23 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-02-09 20:48:23 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-02-09 20:48:40 DEBUG (MainThread) [custom_components.hacs] Running uninstall for custom-components/climate.programmable_thermostat
2021-02-09 20:48:40 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/climate.programmable_thermostat> Getting repository information
2021-02-09 20:48:40 DEBUG (MainThread) [custom_components.hacs] Did not update custom-components/climate.programmable_thermostat, content was not modified
2021-02-09 20:48:40 INFO (MainThread) [custom_components.hacs] <Integration custom-components/climate.programmable_thermostat> Uninstalling
2021-02-09 20:48:40 ERROR (MainThread) [custom_components.hacs] <Integration custom-components/climate.programmable_thermostat> Path /config/custom_components/ is blocked from removal
2021-02-09 20:48:40 ERROR (MainThread) [custom_components.hacs] Could not uninstall
2021-02-09 20:52:24 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for programmable_thermostat which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-09 20:55:01 DEBUG (MainThread) [custom_components.hacs] Running uninstall for custom-components/climate.programmable_thermostat
2021-02-09 20:55:01 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/climate.programmable_thermostat> Getting repository information
2021-02-09 20:55:01 DEBUG (MainThread) [custom_components.hacs] Did not update custom-components/climate.programmable_thermostat, content was not modified
2021-02-09 20:55:01 INFO (MainThread) [custom_components.hacs] <Integration custom-components/climate.programmable_thermostat> Uninstalling
2021-02-09 20:55:01 ERROR (MainThread) [custom_components.hacs] <Integration custom-components/climate.programmable_thermostat> Path /config/custom_components/ is blocked from removal
2021-02-09 20:55:01 ERROR (MainThread) [custom_components.hacs] Could not uninstall
2021-02-09 20:56:47 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2021-02-09 20:59:57 DEBUG (MainThread) [custom_components.hacs] Running uninstall for maxwroc/battery-state-card
2021-02-09 20:59:57 DEBUG (MainThread) [custom_components.hacs] <Plugin maxwroc/battery-state-card> Getting repository information
2021-02-09 20:59:57 DEBUG (MainThread) [custom_components.hacs] Did not update maxwroc/battery-state-card, content was not modified
2021-02-09 20:59:57 INFO (MainThread) [custom_components.hacs] <Plugin maxwroc/battery-state-card> Uninstalling
2021-02-09 20:59:57 DEBUG (MainThread) [custom_components.hacs] <Plugin maxwroc/battery-state-card> Removing /config/www/community/battery-state-card
2021-02-09 20:59:57 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-02-09 20:59:57 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-02-09 21:00:17 DEBUG (MainThread) [custom_components.hacs] Running update for maxwroc/battery-state-card
2021-02-09 21:00:17 DEBUG (MainThread) [custom_components.hacs] <Plugin maxwroc/battery-state-card> Getting repository information
2021-02-09 21:00:17 ERROR (MainThread) [custom_components.hacs] Could not use repository with ID 256292682 ('NoneType' object has no attribute 'attributes')
2021-02-09 21:01:01 DEBUG (MainThread) [custom_components.hacs] Running update for maxwroc/battery-state-card
2021-02-09 21:01:01 DEBUG (MainThread) [custom_components.hacs] <Plugin maxwroc/battery-state-card> Getting repository information
2021-02-09 21:01:02 ERROR (MainThread) [custom_components.hacs] Could not use repository with ID 256292682 ('NoneType' object has no attribute 'attributes')
2021-02-09 21:01:20 DEBUG (MainThread) [custom_components.hacs] Running update for benct/lovelace-battery-entity-row
2021-02-09 21:01:20 DEBUG (MainThread) [custom_components.hacs] <Plugin benct/lovelace-battery-entity-row> Getting repository information
2021-02-09 21:01:21 DEBUG (MainThread) [custom_components.hacs] <Plugin benct/lovelace-battery-entity-row> Running checks against v1.2.0
2021-02-09 21:01:22 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-02-09 21:01:22 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-02-09 21:02:18 DEBUG (MainThread) [custom_components.hacs] Running update for maxwroc/battery-state-card
2021-02-09 21:02:18 DEBUG (MainThread) [custom_components.hacs] <Plugin maxwroc/battery-state-card> Getting repository information
2021-02-09 21:02:19 ERROR (MainThread) [custom_components.hacs] Could not use repository with ID 256292682 ('NoneType' object has no attribute 'attributes')
2021-02-09 21:04:07 DEBUG (MainThread) [custom_components.hacs] Running uninstall for custom-components/climate.programmable_thermostat
2021-02-09 21:04:07 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/climate.programmable_thermostat> Getting repository information
2021-02-09 21:04:07 DEBUG (MainThread) [custom_components.hacs] Did not update custom-components/climate.programmable_thermostat, content was not modified
2021-02-09 21:04:07 INFO (MainThread) [custom_components.hacs] <Integration custom-components/climate.programmable_thermostat> Uninstalling
2021-02-09 21:04:07 ERROR (MainThread) [custom_components.hacs] <Integration custom-components/climate.programmable_thermostat> Path /config/custom_components/ is blocked from removal
2021-02-09 21:04:07 ERROR (MainThread) [custom_components.hacs] Could not uninstall

```

</details>

**Comment by TTLucian** [comment]
After updating HACS to 1.11.1 I still can't uninstall integration repos and I still get this error:
```
2021-02-10 13:33:11 ERROR (MainThread) [custom_components.hacs] <Integration custom-components/climate.programmable_thermostat> Path /config/custom_components/ is blocked from removal
2021-02-10 13:33:11 ERROR (MainThread) [custom_components.hacs] Could not uninstall
```
Is there anything else I should do?
