### ISSUE TITLE
HACS shows an error with ACCEPT_HEADERS in aiogithubapi

### ISSUE THREAD

**Issue by joselcaguilar** [hacs/integration#2114]
## System Health

version | core-2021.7.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.10.45
arch | x86_64
timezone | Europe/Madrid

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 62.3 GB
disk_used | 22.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Visual Studio Code (3.5.0), SSH & Web Terminal (9.0.0), Check Home Assistant configuration (3.8.0), Grafana (7.0.2), Node-RED (9.2.0), InfluxDB (4.1.1), Let's Encrypt (4.11.0), Mosquitto broker (6.0.1), Samba share (9.5.1), Telegraf (0.6.0), MariaDB (2.4.0), AppDaemon 4 (0.6.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 11
views | 5
mode | yaml

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

HACS is not working with HA 2021.7.1 raising an error with ACCEPT_HEADERS in aiogithubapi, however v21.4.0 is installed using pip and I can see it in /usr/lib/python3.9/site-packages, unfortunately it is not loading successfully.

### Reproduction steps

1. Remove HACS folder and integration from the UI
2. Reboot the server
3. Install latest version of HACS following the instructions published on HACS website
4. Try to launch the configuration flow for HACS integration from the UI, error is raised

### Debug logs

```text
Logger: homeassistant.config_entries
Source: config_entries.py:698

Error occurred loading configuration flow for integration hacs: cannot import name 'ACCEPT_HEADERS' from 'aiogithubapi.common.const' (/usr/local/lib/python3.9/site-packages/aiogithubapi/common/const.py)
```

**Comment by ludeeus** [comment]
Delete `/config/deps` and restart Home Assistant

**Comment by joselcaguilar** [comment]
> Delete `/config/deps` and restart Home Assistant

Deleted and restarted, unfortunately the issue remains 😥

**Comment by ppoetsma** [comment]
Same issue here after upgrading to latest core-2021.7.1 and OS 6.1.

**Comment by ludeeus** [comment]
There probably are another custom integration that install an old version.
What custom integrations do you have?

**Comment by ppoetsma** [comment]
I do not know what a "Custom" integration is for you, but this is the full list of what is visible in the UI and configuration.yaml.

- Brother Printer
- Buienradar
- DSMR Slimme Meter
- FreeDNS
- Google Cast
- HACS (not loaded due to the error)
- Mobile App
- Mosquitto broker
- Raspberry Pi Power Supply Checker
- RFLink (currently disabled)
- RFXCOM RFXtrx (currently disabled)
- SpeedTest
- UPnP
- WAQI

**Comment by ludeeus** [comment]
"custom" is anything in the custom_components folder

**Comment by ppoetsma** [comment]
That are only hacs (manifest.json says version 1.13.2) and afvalbeheer (version 4.7.21), the latter installed via hacs.

**Comment by ludeeus** [comment]
Then there should be no conflicts.
Restart Home Assistant untill it works, it's Home Assistant that are responsible to install dependencies, not the integration.

**Comment by ppoetsma** [comment]
I am going to remove the module using https://hacs.xyz/docs/installation/remove and do a clean reinstall.

**Comment by ppoetsma** [comment]
I uninstalled HACS (and its modules, couple of restarts, etc). Next the module installation did not work, same problem as https://github.com/hacs/integration/issues/2089. I executed `ha core rebuild` and then the module could be installed and configured. My problem is solved.

**Comment by joselcaguilar** [comment]
> I uninstalled HACS (and its modules, couple of restarts, etc). Next the module installation did not work, same problem as #2089. I executed `ha core rebuild` and then the module could be installed and configured. My problem is solved. Thanks @ludeeus

Issue resolved with `ha core rebuild`. thanks for your advice @ppoetsma 👍🏼
